name       : libiptcdata
version    : 1.0.4
release    : 2
source     :
    - http://netix.dl.sourceforge.net/project/libiptcdata/libiptcdata/1.0.4/libiptcdata-1.0.4.tar.gz : 79f63b8ce71ee45cefd34efbb66e39a22101443f4060809b8fc29c5eebdcee0e
license    : LGPL-2.0
component  : programming
summary    : libiptcdata is a library for manipulating IPTC metadata
description: "libiptcdata is a library, written in C, for manipulating the International\
    \ Press \nTelecommunications Council (IPTC) metadata stored within multimedia\
    \ files such as images.\n"
optimize   : speed
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
